### ISSUE TITLE
plz add empty params filtering to URL serializer

### ISSUE THREAD

**Issue by bozheville** [frankland/valent#8]
if url param is empty remove it from url

**Comment by tuchk4** [comment]
done

**Comment by tuchk4** [comment]
@bozheville added `isEncodeAllowed(key, value)` [hook:52](https://github.com/frankland/valent/blob/rework/src/serializers/serializer.js#L52) at base serializer and updated [url-serializer:189](https://github.com/frankland/valent/blob/rework/src/serializers/url-serializer.js#L189)
